FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-stage
WORKDIR /app
COPY . ./
RUN dotnet restore && dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build-stage /app/out .

EXPOSE 8080
ENV ASPNETCORE_URLS="http://+:8080"

CMD ["dotnet", "E_commerce_app_dotnet.dll"]
