version: '3.8'

services:
  mongo-1:
    image: mongo:7.0
    container_name: mongo-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 30s
      retries: 5

  app-1:
    build:
      context: .
      target: runtime
    container_name: app-1
    ports:
      - "8080:8080"
    depends_on:
      mongo-1:
        condition: service_healthy
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://admin:password@mongo-1:27017"