[phases.setup]
nixPkgs = ["curl", "bash"]

[phases.install]
commands = [
    "wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh",
    "chmod +x dotnet-install.sh",
    "./dotnet-install.sh --version 9.0.100",
    "export PATH=$HOME/.dotnet:$PATH"
]
